package sl.hr_client.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sl.hr_client.data.bean.DownloadBean;
import sl.hr_client.data.bean.NewsBean;

import sl.hr_client.data.dao.DownloadBeanDao;
import sl.hr_client.data.dao.NewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadBeanDaoConfig;
    private final DaoConfig newsBeanDaoConfig;

    private final DownloadBeanDao downloadBeanDao;
    private final NewsBeanDao newsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadBeanDaoConfig = daoConfigMap.get(DownloadBeanDao.class).clone();
        downloadBeanDaoConfig.initIdentityScope(type);

        newsBeanDaoConfig = daoConfigMap.get(NewsBeanDao.class).clone();
        newsBeanDaoConfig.initIdentityScope(type);

        downloadBeanDao = new DownloadBeanDao(downloadBeanDaoConfig, this);
        newsBeanDao = new NewsBeanDao(newsBeanDaoConfig, this);

        registerDao(DownloadBean.class, downloadBeanDao);
        registerDao(NewsBean.class, newsBeanDao);
    }
    
    public void clear() {
        downloadBeanDaoConfig.getIdentityScope().clear();
        newsBeanDaoConfig.getIdentityScope().clear();
    }

    public DownloadBeanDao getDownloadBeanDao() {
        return downloadBeanDao;
    }

    public NewsBeanDao getNewsBeanDao() {
        return newsBeanDao;
    }

}
